Repository oxcaml/oxcaml, pull requests merged in 2021-07, with the labels that each got.

#80 Backport PR#10205 from upstream
  ocaml/stdlib/.depend
  ocaml/stdlib/camlinternalMod.ml
  ocaml/testsuite/tests/basic-modules/recursive_module_init.ml
  ocaml/testsuite/tests/basic-modules/recursive_module_init.reference
Labels: flambda2

#73 Remove Obj.set_tag and Obj.truncate
  ocaml/stdlib/obj.ml
  ocaml/stdlib/obj.mli
Labels: flambda2

#83 Fix reload for `Icomp` (amd64)
  backend/amd64/reload.ml
  backend/i386/reload.ml
Labels: to-upstream

#72 CMM traps
  backend/CSEgen.ml
  backend/afl_instrument.ml
  backend/amd64/proc.ml
  backend/amd64/selection.ml
  backend/cmm.ml
  backend/cmm.mli
  backend/cmm_helpers.ml
  backend/cmmgen.ml
  backend/comballoc.ml
  backend/deadcode.ml
  backend/debug/available_regs.ml
  backend/interf.ml
  backend/interval.ml
  backend/linearize.ml
  backend/liveness.ml
  backend/liveness.mli
  backend/mach.ml
  backend/mach.mli
  backend/printcmm.ml
  backend/printcmm.mli
  backend/printmach.ml
  backend/reloadgen.ml
  backend/selectgen.ml
  backend/spill.ml
  backend/split.ml
  backend/strmatch.ml
  ocaml/testsuite/tests/asmgen/catch-try-float.cmm
  ocaml/testsuite/tests/asmgen/catch-try.cmm
  ocaml/testsuite/tools/parsecmm.mly
  testsuite/tools/parsecmm.mly
Labels: flambda2

#74 Add a `returns` field to `Cmm.Cextcall`
  backend/afl_instrument.ml
  backend/amd64/selection.ml
  backend/cfg/cfg_intf.ml
  backend/cfg/cfg_to_linear.ml
  backend/cfg/linear_to_cfg.ml
  backend/cmm.ml
  backend/cmm.mli
  backend/cmm_helpers.ml
  backend/cmm_helpers.mli
  backend/cmmgen.ml
  backend/linearize.ml
  backend/liveness.ml
  backend/mach.ml
  backend/mach.mli
  backend/printcmm.ml
  backend/printcmm.mli
  backend/selectgen.ml
  ocaml/testsuite/tools/parsecmm.mly
  testsuite/tools/parsecmm.mly
Labels: flambda2

#71 Obj changes for Flambda 2
  ocaml/stdlib/obj.ml
  ocaml/stdlib/obj.mli
  ocaml/testsuite/tests/warnings/w59.flambda.reference
  ocaml/testsuite/tests/warnings/w59.ml
Labels: flambda2

#61 Distinguish all-float blocks and float arrays
  middle_end/closure/closure.ml
  middle_end/convert_primitives.ml
  middle_end/flambda/closure_conversion.ml
  middle_end/internal_variable_names.ml
  ocaml/boot/ocamlc
  ocaml/bytecomp/bytegen.ml
  ocaml/bytecomp/symtable.ml
  ocaml/lambda/lambda.ml
  ocaml/lambda/lambda.mli
  ocaml/lambda/printlambda.ml
  ocaml/lambda/translcore.ml
  ocaml/lambda/translprim.ml
  ocaml/middle_end/closure/closure.ml
  ocaml/middle_end/convert_primitives.ml
  ocaml/middle_end/flambda/closure_conversion.ml
  ocaml/middle_end/flambda/simplify_primitives.ml
  ocaml/middle_end/internal_variable_names.ml
  ocaml/testsuite/tests/translprim/ref_spec.compilers.reference
  ocaml/tools/dumpobj.ml
Labels: flambda2

#63 Ensure that Lifthenelse has a boolean-valued condition
  ocaml/lambda/matching.ml
  ocaml/lambda/simplif.ml
  ocaml/lambda/switch.ml
Labels: flambda2

#87 Root scanning fixes for Flambda 2
  ocaml/runtime/roots_nat.c
Labels: flambda2

#89 Allow --enable-middle-end=flambda2 etc
  configure.ac
  driver/optcompile.ml
  ocaml/Makefile.config.in
  ocaml/configure
  ocaml/configure.ac
  ocaml/utils/Makefile
  ocaml/utils/config.mlp
Labels: flambda2

#81 Liveness/spill PRs
  backend/liveness.ml
  backend/mach.ml
  backend/mach.mli
  backend/spill.ml
  backend/spill.mli
Labels: flambda2

#92 Better fatal error message in `Selectgen`
  backend/selectgen.ml
Labels: flambda2

#86 Lambda block kinds
  backend/cmmgen.ml
  middle_end/clambda_primitives.ml
  middle_end/clambda_primitives.mli
  middle_end/printclambda.ml
  ocaml/asmcomp/cmmgen.ml
  ocaml/compilerlibs/Makefile.compilerlibs
  ocaml/lambda/lambda.ml
  ocaml/lambda/lambda.mli
  ocaml/lambda/printlambda.ml
  ocaml/lambda/printlambda.mli
  ocaml/middle_end/clambda_primitives.ml
  ocaml/middle_end/clambda_primitives.mli
  ocaml/middle_end/printclambda.ml
  ocaml/testsuite/tests/basic-modules/anonymous.ocamlc.reference
  ocaml/testsuite/tests/basic-modules/anonymous.ocamlopt.flambda.reference
  ocaml/testsuite/tests/basic-modules/anonymous.ocamlopt.reference
  ocaml/testsuite/tests/basic/patmatch_for_multiple.ml
  ocaml/testsuite/tests/basic/patmatch_split_no_or.ml
  ocaml/testsuite/tests/translprim/array_spec.compilers.flat.reference
  ocaml/testsuite/tests/translprim/comparison_table.compilers.reference
  ocaml/testsuite/tests/translprim/ref_spec.compilers.reference
  ocaml/testsuite/tests/typing-gadts/principality-and-gadts.ml
  ocaml/typing/typeopt.ml
Labels: flambda2

#88 Add mutability annotations to Pfield etc.
  backend/cmmgen.ml
  middle_end/clambda_primitives.ml
  middle_end/clambda_primitives.mli
  middle_end/closure/closure.ml
  middle_end/convert_primitives.ml
  middle_end/flambda/alias_analysis.ml
  middle_end/flambda/alias_analysis.mli
  middle_end/flambda/inconstant_idents.ml
  middle_end/flambda/lift_constants.ml
  middle_end/flambda/lift_let_to_initialize_symbol.ml
  middle_end/flambda/ref_to_variables.ml
  middle_end/flambda/simplify_primitives.ml
  middle_end/internal_variable_names.ml
  middle_end/printclambda.ml
  middle_end/printclambda_primitives.ml
  middle_end/semantics_of_primitives.ml
  native_toplevel/opttoploop.ml
  ocaml/asmcomp/cmmgen.ml
  ocaml/boot/ocamlc
  ocaml/boot/ocamllex
  ocaml/bytecomp/bytegen.ml
  ocaml/lambda/lambda.ml
  ocaml/lambda/lambda.mli
  ocaml/lambda/matching.ml
  ocaml/lambda/printlambda.ml
  ocaml/lambda/simplif.ml
  ocaml/lambda/translclass.ml
  ocaml/lambda/translcore.ml
  ocaml/lambda/translmod.ml
  ocaml/lambda/translobj.ml
  ocaml/lambda/translprim.ml
  ocaml/middle_end/clambda_primitives.ml
  ocaml/middle_end/clambda_primitives.mli
  ocaml/middle_end/closure/closure.ml
  ocaml/middle_end/convert_primitives.ml
  ocaml/middle_end/flambda/alias_analysis.ml
  ocaml/middle_end/flambda/alias_analysis.mli
  ocaml/middle_end/flambda/inconstant_idents.ml
  ocaml/middle_end/flambda/lift_constants.ml
  ocaml/middle_end/flambda/lift_let_to_initialize_symbol.ml
  ocaml/middle_end/flambda/ref_to_variables.ml
  ocaml/middle_end/flambda/simplify_primitives.ml
  ocaml/middle_end/internal_variable_names.ml
  ocaml/middle_end/printclambda.ml
  ocaml/middle_end/printclambda_primitives.ml
  ocaml/middle_end/semantics_of_primitives.ml
  ocaml/stdlib/pervasives.ml
  ocaml/stdlib/stdlib.ml
  ocaml/stdlib/stdlib.mli
  ocaml/testsuite/tests/basic-modules/anonymous.ocamlc.reference
  ocaml/testsuite/tests/basic-modules/anonymous.ocamlopt.flambda.reference
  ocaml/testsuite/tests/basic-modules/anonymous.ocamlopt.reference
  ocaml/testsuite/tests/basic/patmatch_split_no_or.ml
  ocaml/toplevel/opttoploop.ml
Labels: flambda2, to-upstream

#95 Build our own ocamlobjinfo from tools/objinfo/ at the root
  Makefile.in
  ocaml/tools/dune
  tools/dune
  tools/objinfo.ml
Labels: flambda2

#96 Fix Selectgen and Spill for probes
  backend/selectgen.ml
  backend/spill.ml
Labels: flambda2

#94 Add Flambda2 case to Cmx_format.export_info
  backend/asmlibrarian.ml
  backend/asmpackager.ml
  dune
  file_formats/cmx_format.mli
  middle_end/compilenv.ml
  tools/objinfo.ml
Labels: flambda2

#97 Backend_impl / Compilenv changes for Flambda 2
  dune
  middle_end/compilenv.ml
  middle_end/compilenv.mli
  middle_end/flambda2/backend_intf/dune
  middle_end/flambda2/backend_intf/flambda2_backend_impl.ml
  middle_end/flambda2/backend_intf/flambda2_backend_impl.mli
  middle_end/flambda2/flambda_backend_intf.mli
  middle_end/flambda2/to_cmm/un_cps.ml
Labels: flambda2

#98 First set of command-line flags for Flambda 2
  middle_end/flambda2/compilenv_deps/flambda_features.ml
  ocaml/driver/main_args.ml
  ocaml/driver/main_args.mli
  ocaml/utils/clflags.ml
  ocaml/utils/clflags.mli
Labels: flambda2

#102 Fix Flambda_features.flambda2_is_enabled
  middle_end/flambda2/compilenv_deps/flambda_features.ml
Labels: flambda2

#101 Formatting of help text for some Flambda 2 options
  ocaml/driver/main_args.ml
Labels: flambda2

#100 Wire in the Flambda 2 inlining flags
  middle_end/flambda2/compilenv_deps/flambda_features.ml
  ocaml/driver/main_args.ml
  ocaml/driver/main_args.mli
  ocaml/utils/clflags.ml
  ocaml/utils/clflags.mli
Labels: flambda2

#103 Wire in the remaining Flambda 2 flags
  middle_end/flambda2/compilenv_deps/flambda_features.ml
  middle_end/flambda2/compilenv_deps/flambda_features.mli
  middle_end/flambda2/from_lambda/closure_conversion.ml
  middle_end/flambda2/simplify/simplify_named.ml
  middle_end/flambda2/simplify/simplify_set_of_closures.ml
  middle_end/flambda2/simplify/typing_helpers/continuation_uses.ml
  middle_end/flambda2/terms/let_cont_expr.rec.ml
  middle_end/flambda2/to_cmm/un_cps_closure.ml
  middle_end/flambda2/to_cmm/un_cps_static.ml
  middle_end/flambda2/types/env/typing_env.rec.ml
  ocaml/driver/main_args.ml
  ocaml/driver/main_args.mli
  ocaml/utils/clflags.ml
  ocaml/utils/clflags.mli
Labels: flambda2

#104 -Oclassic, -O2 and -O3 handling for Flambda 2
  driver/optcompile.ml
  ocaml/driver/compenv.ml
  ocaml/driver/main_args.ml
  ocaml/driver/optcompile.ml
  ocaml/parsing/builtin_attributes.ml
  ocaml/utils/clflags.ml
  ocaml/utils/clflags.mli
Labels: flambda2

#105 Asmgen changes for Flambda 2
  backend/asmgen.ml
  backend/asmgen.mli
Labels: flambda2

#106 Asmpackager for Flambda 2
  backend/asmpackager.ml
  backend/asmpackager.mli
  driver/dune
  driver/flambda_backend_main.ml
  driver/optmaindriver.ml
  driver/optmaindriver.mli
  dune
  middle_end/flambda2/backend_intf/dune
Labels: flambda2

#109 Add /testsuite/tools/Makefile and allow to use Flambda 2 libs (and fix .gitignore)
  .gitignore
  Makefile.in
  testsuite/tools/Makefile
Labels: flambda2

#114 Fix typo in PR#109
  Makefile.in
Labels: flambda2

#110 Minor fix for "lazy" compilation in Matching with Flambda 2
  ocaml/lambda/matching.ml
Labels: flambda2

#107 Wire in Flambda2 driver
  driver/optcompile.ml
  driver/optcompile.mli
  driver/optmaindriver.ml
Labels: flambda2

#108 Set Flambda2 current compilation unit
  middle_end/compilenv.ml
  testsuite/tools/Makefile
Labels: flambda2

#111 Use Closure for stage 0 coldstart build in Flambda 2 mode
  .gitignore
  Makefile.in
  configure.ac
Labels: flambda2

#113 Fix typo in Un_cps
  middle_end/flambda2/to_cmm/un_cps.ml
Labels: flambda2

#115 Extend conditions to include flambda2
  ocaml/lambda/translattribute.ml
  ocaml/lambda/translcore.ml
  ocaml/parsing/builtin_attributes.ml
  ocaml/testsuite/tests/float-unboxing/float_subst_boxed_number.ml
Labels: flambda2

#118 Magic numbers for cmx and cmxa files
  ocaml/utils/config.mlp
  ocaml/utils/misc.ml
Labels: flambda2

#116 Add Flambda 2 CI workflow
  .github/workflows/flambda2.yml
  Makefile.in
  testsuite/flambda2-test-list
Labels: flambda2

#121 Resurrect [@inline never] annotations in camlinternalMod
  ocaml/stdlib/camlinternalMod.ml
Labels: flambda2

#122 Avoid passing a "\n" argument to `configure`
  Makefile.in
Labels: flambda2

#123 `runtest-upstream` typo
  Makefile.in
Labels: flambda2

#120 Make ocamlobjinfo work for Flambda 2 .cmx files
  tools/objinfo.ml
Labels: flambda2

#119 Fix error with Record_unboxed (bug in block kind patch)
  ocaml/typing/typeopt.ml
Labels: bug, flambda2

#126 Fix computation of extra_args during CPS conversion of Lstaticraise
  middle_end/flambda2/from_lambda/lambda_to_flambda.ml
  middle_end/flambda2/tests/mlexamples/extra_args_and_staticraise.ml
Labels: bug, flambda2
